// <auto-generated />
using System;
using Icarus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Icarus.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IcarusDbContext))]
    [Migration("20260906004723_CriarModeloInicial")]
    partial class CriarModeloInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Icarus.Domain.Entities.Campanha", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cor");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<long>("EpicoId")
                        .HasColumnType("bigint")
                        .HasColumnName("epico_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("PrazoFim")
                        .HasColumnType("date")
                        .HasColumnName("prazo_fim");

                    b.Property<DateOnly>("PrazoInicio")
                        .HasColumnType("date")
                        .HasColumnName("prazo_inicio");

                    b.Property<int>("Priorizacao")
                        .HasColumnType("integer")
                        .HasColumnName("priorizacao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<string>("Unidade")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unidade");

                    b.Property<decimal?>("ValorAtual")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_atual");

                    b.Property<decimal?>("ValorMensurado")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_mensurado");

                    b.HasKey("Id")
                        .HasName("pk_campanha");

                    b.HasIndex("EpicoId")
                        .HasDatabaseName("ix_campanha_epico_id");

                    b.ToTable("campanha", (string)null);
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Diario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataRegistro")
                        .HasColumnType("date")
                        .HasColumnName("data_registro");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_diario");

                    b.HasIndex("UsuarioId", "DataRegistro")
                        .HasDatabaseName("ix_diario_usuario_id_data_registro");

                    b.ToTable("diario", (string)null);
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Epico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaDaVida")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("area_da_vida");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cor");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("PrazoFim")
                        .HasColumnType("date")
                        .HasColumnName("prazo_fim");

                    b.Property<DateOnly>("PrazoInicio")
                        .HasColumnType("date")
                        .HasColumnName("prazo_inicio");

                    b.Property<int>("Priorizacao")
                        .HasColumnType("integer")
                        .HasColumnName("priorizacao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_epico");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_epico_usuario_id");

                    b.HasIndex("UsuarioId", "PrazoFim")
                        .HasDatabaseName("ix_epico_usuario_id_prazo_fim");

                    b.ToTable("epico", (string)null);
                });

            modelBuilder.Entity("Icarus.Domain.Entities.InventarioItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_inventario_item");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_inventario_item_item_id");

                    b.HasIndex("UsuarioId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventario_item_usuario_id_item_id");

                    b.ToTable("inventario_item", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventario_item_quantidade_nao_negativa", "quantidade >= 0");
                        });
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("ControlaApp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("controla_app");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<int>("Valor")
                        .HasColumnType("integer")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_item");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_item_usuario_id");

                    b.ToTable("item", null, t =>
                        {
                            t.HasCheckConstraint("ck_item_valor_nao_negativo", "valor >= 0");
                        });
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Missao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Beneficio")
                        .HasColumnType("text")
                        .HasColumnName("beneficio");

                    b.Property<long?>("CampanhaId")
                        .HasColumnType("bigint")
                        .HasColumnName("campanha_id");

                    b.Property<DateTimeOffset?>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("concluida_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataLimite")
                        .HasColumnType("date")
                        .HasColumnName("data_limite");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<DateTimeOffset>("Horario")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("horario");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("integer")
                        .HasColumnName("pontuacao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_missao");

                    b.HasIndex("CampanhaId")
                        .HasDatabaseName("ix_missao_campanha_id");

                    b.HasIndex("Horario")
                        .HasDatabaseName("ix_missao_horario");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_missao_status");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_missao_usuario_id");

                    b.ToTable("missao", null, t =>
                        {
                            t.HasCheckConstraint("ck_missao_pontuacao_nao_negativa", "pontuacao >= 0");
                        });
                });

            modelBuilder.Entity("Icarus.Domain.Entities.MissaoIA", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Beneficio")
                        .HasColumnType("text")
                        .HasColumnName("beneficio");

                    b.Property<long?>("CampanhaId")
                        .HasColumnType("bigint")
                        .HasColumnName("campanha_id");

                    b.Property<DateTimeOffset?>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("concluida_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataLimite")
                        .HasColumnType("date")
                        .HasColumnName("data_limite");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<DateTimeOffset>("Horario")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("horario");

                    b.Property<long?>("MissaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("missao_id");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("integer")
                        .HasColumnName("pontuacao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StatusAprovacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_aprovacao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_missao_ia");

                    b.HasIndex("CampanhaId")
                        .HasDatabaseName("ix_missao_ia_campanha_id");

                    b.HasIndex("MissaoId")
                        .HasDatabaseName("ix_missao_ia_missao_id");

                    b.HasIndex("StatusAprovacao")
                        .HasDatabaseName("ix_missao_ia_status_aprovacao");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_missao_ia_usuario_id");

                    b.ToTable("missao_ia", null, t =>
                        {
                            t.HasCheckConstraint("ck_missao_ia_pontuacao_nao_negativa", "pontuacao >= 0");
                        });
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Ocorrencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset?>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("concluida_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataPrevista")
                        .HasColumnType("date")
                        .HasColumnName("data_prevista");

                    b.Property<long>("MissaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("missao_id");

                    b.Property<DateTimeOffset?>("RealizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("realizada_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_ocorrencia");

                    b.HasIndex("MissaoId", "DataPrevista")
                        .IsUnique()
                        .HasDatabaseName("ix_ocorrencia_missao_id_data_prevista");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ocorrencia_status");

                    b.ToTable("ocorrencia", (string)null);
                });

            modelBuilder.Entity("Icarus.Domain.Entities.MovimentacaoPontos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    b.Property<long?>("OcorrenciaId")
                        .HasColumnType("bigint")
                        .HasColumnName("ocorrencia_id");

                    b.Property<long>("Quantidade")
                        .HasColumnType("bigint")
                        .HasColumnName("quantidade");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_movimentacao_pontos");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_movimentacao_pontos_item_id");

                    b.HasIndex("OcorrenciaId")
                        .HasDatabaseName("ix_movimentacao_pontos_ocorrencia_id");

                    b.HasIndex("UsuarioId", "CriadoEm")
                        .HasDatabaseName("ix_movimentacao_pontos_usuario_id_criado_em");

                    b.HasIndex("UsuarioId", "Tipo")
                        .HasDatabaseName("ix_movimentacao_pontos_usuario_id_tipo");

                    b.ToTable("movimentacao_pontos", (string)null);
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Recorrencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<long>("MissaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("missao_id");

                    b.Property<string>("Regra")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("regra");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_recorrencia");

                    b.HasIndex("MissaoId")
                        .IsUnique()
                        .HasDatabaseName("ix_recorrencia_missao_id");

                    b.ToTable("recorrencia", (string)null);
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Relatorio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conteudo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("PeriodoFim")
                        .HasColumnType("date")
                        .HasColumnName("periodo_fim");

                    b.Property<DateOnly>("PeriodoInicio")
                        .HasColumnType("date")
                        .HasColumnName("periodo_inicio");

                    b.Property<string>("Texto")
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_relatorio");

                    b.HasIndex("UsuarioId", "Tipo", "PeriodoInicio", "PeriodoFim")
                        .HasDatabaseName("ix_relatorio_usuario_id_tipo_periodo_inicio_periodo_fim");

                    b.ToTable("relatorio", (string)null);
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Rotina", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaTrabalho")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("area_trabalho");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("HorasLivres")
                        .HasColumnType("integer")
                        .HasColumnName("horas_livres");

                    b.Property<int>("HorasOcupado")
                        .HasColumnType("integer")
                        .HasColumnName("horas_ocupado");

                    b.Property<string>("ModalidadeTrabalho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modalidade_trabalho");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<DateOnly?>("VigenciaFim")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_fim");

                    b.Property<DateOnly>("VigenciaInicio")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_inicio");

                    b.HasKey("Id")
                        .HasName("pk_rotina");

                    b.HasIndex("UsuarioId", "VigenciaInicio", "VigenciaFim")
                        .HasDatabaseName("ix_rotina_usuario_id_vigencia_inicio_vigencia_fim");

                    b.ToTable("rotina", (string)null);
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<long>("SaldoPontos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("saldo_pontos");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_email");

                    b.ToTable("usuario", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuario_saldo_pontos_nao_negativo", "saldo_pontos >= 0");
                        });
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Campanha", b =>
                {
                    b.HasOne("Icarus.Domain.Entities.Epico", "Epico")
                        .WithMany("Campanhas")
                        .HasForeignKey("EpicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campanha_epicos_epico_id");

                    b.Navigation("Epico");
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Diario", b =>
                {
                    b.HasOne("Icarus.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Diarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diario_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Epico", b =>
                {
                    b.HasOne("Icarus.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Epicos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_epico_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Icarus.Domain.Entities.InventarioItem", b =>
                {
                    b.HasOne("Icarus.Domain.Entities.Item", "Item")
                        .WithMany("InventarioItens")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventario_item_itens_item_id");

                    b.HasOne("Icarus.Domain.Entities.Usuario", "Usuario")
                        .WithMany("InventarioItens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventario_item_usuarios_usuario_id");

                    b.Navigation("Item");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Item", b =>
                {
                    b.HasOne("Icarus.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Itens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Missao", b =>
                {
                    b.HasOne("Icarus.Domain.Entities.Campanha", "Campanha")
                        .WithMany("Missoes")
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_missao_campanha_campanha_id");

                    b.HasOne("Icarus.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Missoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_missao_usuarios_usuario_id");

                    b.Navigation("Campanha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Icarus.Domain.Entities.MissaoIA", b =>
                {
                    b.HasOne("Icarus.Domain.Entities.Campanha", "Campanha")
                        .WithMany("MissoesIA")
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_missao_ia_campanha_campanha_id");

                    b.HasOne("Icarus.Domain.Entities.Missao", "Missao")
                        .WithMany("MissoesIA")
                        .HasForeignKey("MissaoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_missao_ia_missao_missao_id");

                    b.HasOne("Icarus.Domain.Entities.Usuario", "Usuario")
                        .WithMany("MissoesIA")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_missao_ia_usuarios_usuario_id");

                    b.Navigation("Campanha");

                    b.Navigation("Missao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Ocorrencia", b =>
                {
                    b.HasOne("Icarus.Domain.Entities.Missao", "Missao")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("MissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ocorrencia_missao_missao_id");

                    b.Navigation("Missao");
                });

            modelBuilder.Entity("Icarus.Domain.Entities.MovimentacaoPontos", b =>
                {
                    b.HasOne("Icarus.Domain.Entities.Item", "Item")
                        .WithMany("MovimentacoesPontos")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movimentacao_pontos_item_item_id");

                    b.HasOne("Icarus.Domain.Entities.Ocorrencia", "Ocorrencia")
                        .WithMany("MovimentacoesPontos")
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movimentacao_pontos_ocorrencia_ocorrencia_id");

                    b.HasOne("Icarus.Domain.Entities.Usuario", "Usuario")
                        .WithMany("MovimentacoesPontos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacao_pontos_usuarios_usuario_id");

                    b.Navigation("Item");

                    b.Navigation("Ocorrencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Recorrencia", b =>
                {
                    b.HasOne("Icarus.Domain.Entities.Missao", "Missao")
                        .WithOne("Recorrencia")
                        .HasForeignKey("Icarus.Domain.Entities.Recorrencia", "MissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recorrencia_missao_missao_id");

                    b.Navigation("Missao");
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Relatorio", b =>
                {
                    b.HasOne("Icarus.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Relatorios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relatorio_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Rotina", b =>
                {
                    b.HasOne("Icarus.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Rotinas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rotina_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Campanha", b =>
                {
                    b.Navigation("Missoes");

                    b.Navigation("MissoesIA");
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Epico", b =>
                {
                    b.Navigation("Campanhas");
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Item", b =>
                {
                    b.Navigation("InventarioItens");

                    b.Navigation("MovimentacoesPontos");
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Missao", b =>
                {
                    b.Navigation("MissoesIA");

                    b.Navigation("Ocorrencias");

                    b.Navigation("Recorrencia");
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Ocorrencia", b =>
                {
                    b.Navigation("MovimentacoesPontos");
                });

            modelBuilder.Entity("Icarus.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Diarios");

                    b.Navigation("Epicos");

                    b.Navigation("InventarioItens");

                    b.Navigation("Itens");

                    b.Navigation("Missoes");

                    b.Navigation("MissoesIA");

                    b.Navigation("MovimentacoesPontos");

                    b.Navigation("Relatorios");

                    b.Navigation("Rotinas");
                });
#pragma warning restore 612, 618
        }
    }
}
